# eg. Can be used to host your internal composer package registry on github pages.
name: Composer repository

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: trackleft/packagist@v1
        with:
          token: ${{ secrets.TOKEN_GITHUB_PACKAGIST }} # App/OAuth token, PAT
      - env:
          GIT_EMAIL: bot@github.com
          GIT_NAME: cool-bot
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/
          git commit -m "Re-built repository assets"
          git push
