# eg. Can be used to host your internal composer package registry on github pages.
name: Composer repository

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - env:
          COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.TOKEN_GITHUB_PACKAGIST }}"}}'
          COMPOSER_HOME: /tmp/.satis-build
        run: |
          mkdir /tmp/.satis-build
          echo "{}" > /tmp/.satis-build/composer.json

          composer g require composer/satis:dev-main --prefer-dist \
            --no-cache --no-progress --no-interaction -o \
            --ignore-platform-reqs

          php $COMPOSER_HOME/vendor/bin/satis build satis.json -n

          if cat ${{ inputs.satis_config }} | jq .archive -e; then
            php $COMPOSER_HOME/vendor/bin/satis purge satis.json -n
          fi

        shell: bash
      - run: |
          rm -rf $COMPOSER_HOME
        shell: bash
      - env:
          GIT_EMAIL: bot@github.com
          GIT_NAME: cool-bot
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add docs/
          git commit -m "Re-built repository assets"
          git push
